version: '3.8'

services:
  php-httpd:
    container_name: httpd-php
    build:
      context: .
      dockerfile: php-apache.dockerfile
    ports:
      - 8080:80
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6.7
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - "~/.cache/TecWeb/mariadb-data:/var/lib/mysql"
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "passwd"
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'passwd'
      MYSQL_DATABASE: 'db'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
